FROM debian:11

RUN apt-get update && \
    apt-get install sudo && \
    apt-get install -y init && \
    apt-get install -y python3 && \
    apt-get install -y openssh-server && \
    apt-get clean

RUN echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir /var/run/sshd

RUN adduser --shell /bin/bash --gecos "" ansible

RUN echo 'ansible:1234' | chpasswd

CMD ["/usr/sbin/sshd", "-D"]