- name: Uri tutorial
  hosts: localhost
  tasks:
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      cron:
        name: "check dirs"
        minute: "0"
        hour: "5,2"
        job: "ls -alh > /dev/null"

    - name: Creates a cron file under /etc/cron.d
      ansible.builtin.cron:
        name: yum autoupdate
        weekday: "2"
        minute: "0"
        hour: "12"
        user: root
        job: "YUMINTERACTIVE=0 /usr/sbin/yum-autoupdate"
        cron_file: ansible_yum-autoupdate

    - name: Removes a cron file from under /etc/cron.d
      ansible.builtin.cron:
        name: "yum autoupdate"
        cron_file: ansible_yum-autoupdate
        state: absent