---
- name: Installing mariadb-server
  apt:
    pkg: mariadb-server
    state: present
    update_cache: yes
    
- name: Start MariaDB
  service:
    name: mariadb
    state: started

- name: Installing dependencies
  apt:
    pkg: [ 'php-mysql', 'python3-pymysql' ]
    state: present
    update_cache: yes

- name: Create mysql database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create mysql user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: '*.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock