---
- name: Install packages
  apt:
    pkg: ['php-pear', 'php-fpm', 'php-dev', 'php-zip', 'php-curl',
          'php-xmlrpc', 'php-gd', 'php-mysql', 'php-mbstring', 'php-xml']
    update_cache: yes
    state: present
  notify:
  - Start PHP-FPM service

- name: Get PHP FPM version
  shell: php -r "echo PHP_VERSION;" | grep -o '[0-9]\.[0-9]'
  register: 'php_version'