- name: Copy tutorial
  hosts: localhost
  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ~/daghan/foo.conf
        dest: ~/foo.conf
        owner: daghan
        group: daghan
        mode: '0644'