- name: Lineinfile tutorial
  hosts: localhost
  tasks:
    - name: Replace line
      lineinfile:
        path: ~/daghan/config
        regexp: '^NAME='
        line: NAME=Hello Ansible
      
    - name: Remove line
      lineinfile:
        path: ~/daghan/config
        state: absent
        regexp: '^DATE'