- name: Uri tutorial
  hosts: localhost
  tasks:
    - name: Check that a page returns a status 200 and fail if the word Ansible is not in the page contents
      uri:
        url: https://www.ansible.com
        return_content: yes
      register: this
      failed_when: "'Ansible' not in this.content"
      tags: match

    - name: Upload a file via multipart/form-multipart
      ansible.builtin.uri:
        url: https://httpbin.org/post
        method: POST
        body_format: form-multipart
        body:
          file1:
            filename: /bin/true
            mime_type: application/octet-stream
          file2:
            content: text based file content
            filename: stat.yml
            mime_type: text/plain
          text_form_field: value
      tags: upload

    - name: POST from contents of local file
      ansible.builtin.uri:
        url: https://httpbin.org/post
        method: POST
        src: file.json
      tags: post


